# Generated by Django 4.1.4 on 2022-12-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0003_remove_trait_trait"),
        ("pets", "0002_remove_pet_trait"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="trait",
            field=models.ManyToManyField(related_name="pets", to="traits.trait"),
        ),
    ]
