# Generated by Django 4.1.4 on 2022-12-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0004_rename_trait_pet_traits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="traits",
        ),
    ]
