# Generated by Django 4.1.4 on 2022-12-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0002_remove_pet_trait"),
        ("traits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trait",
            name="trait",
            field=models.ManyToManyField(related_name="traits", to="pets.pet"),
        ),
    ]
