# Generated by Django 4.1.4 on 2022-12-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0002_trait_trait"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trait",
            name="trait",
        ),
    ]
