# Generated by Django 4.1.4 on 2022-12-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0005_remove_pet_traits"),
        ("traits", "0003_remove_trait_trait"),
    ]

    operations = [
        migrations.AddField(
            model_name="trait",
            name="pets",
            field=models.ManyToManyField(related_name="traits", to="pets.pet"),
        ),
    ]
